server:
  port: 8081
spring:
  main:
    allow-bean-definition-overriding: true
  redis:
    host: localhost
    port: 6379
    database: 1

  datasource:
    url: jdbc:mysql://localhost:3306/blog?characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: 21wlw
    password: 21wlw123
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto

oss:
  accessKey: Oa6F-tvzxn0MwR6SgCUJwIEv02AhJzFlxxmYn_1P
  secretKey: lUEbnGVTTUWs92SY_UF6ewxuc1kCOkRnEY2x_ga2
  bucket: even-blog